trigger:
  branches:
    include:
      - main  # Replace with your main branch name

stages:
  - stage: Build
    displayName: 'Build and Test'
    jobs:
      - job: BuildAndTest
        displayName: 'Build and Test'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '16.x'
              displayName: 'Install Node.js'

          - script: |
              npm install
              npm run build
            displayName: 'Install Dependencies and Build'

  - stage: PlanAndDeploy
    displayName: 'Terraform Plan and Apply'
    jobs:
      - job: TerraformPlan
        displayName: 'Terraform Plan'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: 'latest'
          
          - script: |
              terraform --version
              terraform init -backend-config="storage_account_name=$(storageAccountName)" \
                             -backend-config="container_name=$(containerName)" \
                             -backend-config="key=$(key)" \
                             -backend-config="access_key=$(accessKey)"
              terraform plan -out=tfplan
            displayName: 'Terraform Init and Plan'

      - job: TerraformApply
        displayName: 'Terraform Apply'
        dependsOn: TerraformPlan
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: 'latest'
          
          - script: |
              terraform --version
              terraform init -backend-config="storage_account_name=$(storageAccountName)" \
                             -backend-config="container_name=$(containerName)" \
                             -backend-config="key=$(key)" \
                             -backend-config="access_key=$(accessKey)"
              terraform apply -auto-approve tfplan
            displayName: 'Terraform Init and Apply'
